---
title: "NetworkDataCompanion Quickstart Guide"
author: "Kate Hoff Shutta"
output: 
  rmdformats::robobook:
    code_folding: show
    toc_depth: 3
bibliography: demo.bib  
link-citations: true
---

# About NetworkDataCompanion


# Prepare the workspace

```{R, message=F}
library(NetworkDataCompanion)
```

# Data used in this tutorial

The data used in this tutorial are from the TCGA COAD analysis presented in @fanfani2024reproducible and can be downloaded from the Harvard Dataverse here: https://doi.org/10.7910/DVN/MCSSYJ 

For reference on the source of the data, the full workflow of the COAD analysis is available at https://github.com/QuackenbushLab/tcga-data-supplement/.

Data acknowledgement: These data were generated by the TCGA Research Network: https://www.cancer.gov/tcga.

# Working with the NetworkDataCompanion Object

The most simple way to get started with `NetworkDataCompanion` is to create an oject using the `CreateNetworkDataCompanionObject` function with an empty argument. Because it is a Companion, we like to call it `my_friend`: 

```{R}
my_friend = NetworkDataCompanion::CreateNetworkDataCompanionObject()
```

There are a few built-in attributes that will be accessible to the functions of the Companion:

```{R}
ls(my_friend)
```

Of these, `gene_mapping` and `sample_type_mapping` are loaded with the empty constructor. For the other attributes, we must supply a patient data file and TCGA cancer type. For the COAD example, we can use the following:

```{R}
datapath = "../inst/extdata/tcga-data-supplement/data/processed/batch-coad-subtype-20240510/tcga_coad_cms1/"
patient_data = paste0(datapath,"data_download/clinical/clinical_patient_coad.csv")
```

We input these to the constructor to load the relevant data into the Companion object: 

```{R}
my_coad_friend = NetworkDataCompanion::CreateNetworkDataCompanionObject(clinical_patient_file = patient_data,project_name = "COAD")
```

Now, we can see the other attributes. The project name helps us keep track of which cancer we are working with:

```{R}
my_coad_friend$project_name
```

The clinical patient data stores TCGA barcodes and a range of other patient-level information:

```{R}
my_coad_friend$clinical_patient_data[1:5,1:5]
```
The `TCGA_purities` attribute contains the information about tumor purity for each sample. Because these TCGA data are from bulk tissue, there may be some non-tumor cells in the each sample as well. Higher purity samples will give more accurate depiction of the tumor microenvironment and the user may wish to filter based on purity.

```{R}
head(my_coad_friend$TCGA_purities)
```

# NetworkDataCompanion Functions

The `tcga-data-nf` workflow retrieves five different data types: clinical data, expression, mutations, copy number variation (CNV) data, and methylation. The clinical data is used in the Companion object constructor. The other data types can be wrangled with the Companion member functions.

First, we define paths to the data:

```{R}
exp_datapath = paste0(datapath,"data_download/recount3/tcga_coad_cms1.rds") 
mut_datapath = paste0(datapath,"data_download/mutations/tcga_coad_cms1_mutations.txt") 
mut_pivot_datapath = paste0(datapath, "data_download/mutations/tcga_coad_cms1_mutations_pivot.csv")
cnv_datapath = paste0(datapath, "data_download/cnv/tcga_coad_cms1.csv")
meth_datapath = paste0(datapath, "data_download/methylation/tcga_coad_cms1_methylations.txt")
```

## Functions for working with expression

<!-- ```{R} -->
<!-- # Read RDS expression data -->
<!-- test_exp_rds = readRDS(exp_data) -->
<!-- ``` -->

<!-- The function `extractSampleAndGeneInfo` provides a way to get metadata from the RangedSummarizedExperiment object that stores the expression data download. -->

<!-- ```{R} -->
<!-- rds_info = my_friend$extractSampleAndGeneInfo(test_exp_rds) -->
<!-- rds_sample_info = rds_info$rds_sample_info -->
<!-- rds_sample_info[1:3,1:3] -->

<!-- rds_gene_info = rds_info$rds_gene_info -->
<!-- rds_gene_info[1:3,1:3] -->
<!-- ``` -->

<!-- We can get information about a particular set of genes using either the names or the Ensembl IDs.  -->

<!-- From gene names: -->

<!-- ```{R} -->
<!-- rds_gene_info$gene_name[1:3] -->
<!-- gene_info_from_names = my_friend$getGeneInfo(rds_gene_info$gene_name) -->
<!-- gene_info_from_names[1:3,] -->
<!-- ``` -->

<!-- From Ensembl IDs:  -->

<!-- ```{R} -->
<!-- rds_gene_info$gene_id[1:3] -->
<!-- genes_info_from_ids = my_friend$getGeneInfo(rds_gene_info$gene_id) -->
<!-- genes_info_from_ids[1:3,] -->
<!-- ``` -->

<!-- We can also convert between gene name and Ensembl ID and vice versa: -->

<!-- ```{R} -->
<!-- genes_from_names_to_ids = data.frame(my_friend$geneNameToENSG(rds_gene_info$gene_name)) -->
<!-- genes_from_ids_to_names = data.frame(my_friend$geneENSGToName(rds_gene_info$gene_id)) -->
<!-- ``` -->

<!-- A function for normalization takes a RangedSummarizedExperiment as input and returns three matrices: raw counts, TPM. and log(TPM + 1). -->

<!-- ```{R} -->
<!-- # Normalize data -->
<!-- test_exp_all = my_friend$logTPMNormalization(test_exp_rds) -->
<!-- test_exp_count = test_exp_all$counts -->
<!-- test_exp_tpm = test_exp_all$TPM -->
<!-- test_exp_logtpm = test_exp_all$logTPM -->
<!-- ``` -->

## Functions for working with mutations

## Functions for working with methylation

# References
